name: publish

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: Build and publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          scope: "phollome"
          registry-url: https://registry.npmjs.org/

      - run: yarn install
      - run: yarn build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
