name: test

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Test and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn test
      - run: yarn codecov --token="${{ secrets.CODECOV_TOKEN }}"
